# Generated by Django 5.1.4 on 2025-04-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_signature', models.ImageField(upload_to='uploaded_signatures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usersignature',
            name='original_signature',
            field=models.ImageField(upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='verificationattempt',
            name='result',
            field=models.CharField(choices=[('Real', 'Real'), ('Fake', 'Fake')], max_length=10),
        ),
        migrations.AlterField(
            model_name='verificationattempt',
            name='uploaded_signature',
            field=models.ImageField(upload_to='verification_attempts/'),
        ),
    ]
