# Generated by Django 5.1.4 on 2025-04-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_signatureverification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(upload_to='original_signatures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersignature',
            name='original_signature',
        ),
    ]
